export { default as AuthService } from './auth/auth.service'
export { default as DashboardService } from './dashboard/dashboard.service'
export { default as AdminsService } from './admins/admins.service'
export { default as DirectionService } from './directions/directions.service'
export { default as TeachersService } from './teachers/teachers.service'
export { default as GroupsService } from './groups/groups.service'
export { default as StudentsService } from './students/sudents.service'
export { default as GroupService } from './group/group.service'
