export { default as Login } from './login/Login'
export { default as RequireAuth } from './requireAuth/RequireAuth'
export { default as RedirectRole } from './redirectRole/RedirectRole'
export { default as Statistics } from './admin/Statistics'
export { default as Admins } from './admin/Admins'
export { default as Directions } from './admin/Directions'
export { default as Teachers } from './admin/Teachers'
export { default as Groups } from './groups/Groups'
