export { default as AdminLayout } from './layouts/admin/AdminLayout'
export { default as StatisticsCards } from './admin/statistics/StatisticsCards'
export { default as StatisticsDirections } from './admin/statistics/StatisticsDirections'
export { default as AdminsList } from './admin/admins/AdminsList'
export { default as DirectionsList } from './admin/directions/DirectionsList'
export { default as TeachersTable } from './admin/teachers/TeachersTable'
export { default as GroupsTable } from './groups/GroupsTable'
